name: Run make check
runs:
  using: composite
  steps:
    - name: autogen
      run: ./autogen.sh
      shell: bash
    - name: configure
      run: ./configure
      shell: bash
    - name: make all
      run: make all
      shell: bash
    - name: make check
      run: make check || ( tail -n999 testsuite/*.log && false )
      shell: bash
    - name: make distcheck
      run: make distcheck || ( tail -n999 testsuite/*.log && false )
      shell: bash

    - name: Show testsuite logs
      run: tail -n999 testsuite/*.log
      shell: bash
