name: Report Cirrus CI status

on:
  check_suite:
    type: ['completed']

jobs:
  continue:
    name: After Cirrus CI
    if: github.event.check_suite.app.name == 'Cirrus CI'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Cirrus CI ${{ github.event.check_suite.conclusion }} on ${{ github.event.check_suite.head_branch }} branch!"
          echo "SHA ${{ github.event.check_suite.head_sha }}"
          echo $MESSAGE
          echo "See https://cirrus-ci.com/github/fperrin/i-dunno for details"
          [ "${{ github.event.check_suite.conclusion }}" == "success" ]
